### PR TITLE
VOSICapabilities / TAPRegExt / VOResource

### PR DESCRIPTION
**Pull request by jwfraustro**
Adds complete definitions for the TAPRegExt, VOResource, and VOSI Capabilities specifications.

In order to fully cover the relatively simple spec of VOSI Capabilities, the full standards of TAPRegExt and VOResource need to be implemented. This PR additionally adds documentation and tests for each of the standards. 

An updated RTD page for the dev release is available here: https://vo-models.readthedocs.io/v0.4.0.dev0/

### CODE REVIEW

**Comment by jwfraustro** [comment]
This MR has been successfully deployed in the vo-tap project and produces valid `/capabilities` responses verified by taplint. The full breadth of the specification is difficult to test but this project has been able to additionally successfully consume the capabilities responses of other services. For example, consuming IRSA's TAP `/capabilities` response:

```
from vo_models.vosi.capabilities.models import VOSICapabilities
import requests

IRSA_CAPABILITIES = "https://irsa.ipac.caltech.edu/TAP/capabilities"

irsa_cap_resp = requests.get(IRSA_CAPABILITIES)
irsa_cap_model = VOSICapabilities.from_xml(irsa_cap_resp.content)

print(irsa_cap_model)
```
successfully gives you the equivalent `VOSICapabilities` model (truncated here):

```
VOSICapabilities(
    capability=[
        Capability(...)
            ],
        ),
        Capability(...)
            ],
        ),
        Capability(...)
            ],
        ),
        TableAccess(
            standard_id="ivo://ivoa.net/std/TAP",
            type="tr:TableAccess",
            validation_level=[],
            description=None,
            interface=[
                Interface(
                    version="1.0",
                    role="std",
                    type="vod:ParamHTTP",
                    access_url=[AccessURL(value=Url("https://irsa.ipac.caltech.edu/TAP/"), use="base")],
                    mirror_url=[],
                    security_method=[
                        SecurityMethod(standard_id=None),
                        SecurityMethod(standard_id=Url("ivo://ivoa.net/sso#cookie")),
                    ],
                    test_querystring=None,
                )
            ],
            data_model=[],
            language=[
                Language(
                    name="ADQL",
                    version=[Version(value="2.0", ivo_id="ivo://ivoa.net/std/ADQL#v2.0")],
                    description="ADQL-2.0",
                    language_features=[
                        LanguageFeatureList(
                            feature=[
                                LanguageFeature(form="POINT", description=None),
                                LanguageFeature(form="CIRCLE", description=None),
                                LanguageFeature(form="BOX", description=None),
                          ...

**Review by theresadower — COMMENTED** [review]
I just discovered through unrelated testing that dataModel listings under /capabilities aren't showing up in the MAST operational TAP service, though both the taplint validator and some pyvo functionality relies on them. Adding that support to the Capabilities section, whether autodetected or through some configuration, would be really helpful for validation and usability of any TAP builds using this code.

example:
`<dataModel ivo-id="ivo://ivoa.net/std/ObsCore#core-1.1">ObsCore-1.1</dataModel>`

**Comment by theresadower** [comment]
I just wanted to say the readthedocs looks really good, and is so much more navigable and helpful than trying to learn this through the standards documents.

**Comment by jwfraustro** [comment]
> I just discovered through unrelated testing that dataModel listings under /capabilities aren't showing up in the MAST operational TAP service, though both the taplint validator and some pyvo functionality relies on them. Adding that support to the Capabilities section, whether autodetected or through some configuration, would be really helpful for validation and usability of any TAP builds using this code.
> 
> example: `<dataModel ivo-id="ivo://ivoa.net/std/ObsCore#core-1.1">ObsCore-1.1</dataModel>`

Following up on this, the [model in TAPRegExt here](https://github.com/spacetelescope/vo-models/blob/3921b08ee9b3d717af9f2dec1a285e3cc3fbe64b/vo_models/tapregext/models.py#L18), `DataModelType` is used to represent this. For example,

```
DataModelType(ivo_id="ivo://ivoa.net/std/ObsCore#core-1.1", value="ObsCore-1.1")
```

This has been added to the MAST development deploy and is confirmed as valid by taplint.

**Review by theresadower — APPROVED** [review]
Confirmed the dataModel update

**Pull request merged**
